// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func VpcResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The target vpc id.",
				MarkdownDescription: "The target vpc id.",
			},
			"ip_range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A private address range that you select during creation, such as the default value of 10.240.0.0/16. Because the virtual network is dedicated to your use, you may use whatever IP address range you like.",
				MarkdownDescription: "A private address range that you select during creation, such as the default value of 10.240.0.0/16. Because the virtual network is dedicated to your use, you may use whatever IP address range you like.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "A name to help identify this VPC.",
				MarkdownDescription: "A name to help identify this VPC.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(0, 250),
				},
			},
		},
	}
}

type VpcModel struct {
	Id      types.Int64  `tfsdk:"id"`
	IpRange types.String `tfsdk:"ip_range"`
	Name    types.String `tfsdk:"name"`
}
