# https://developer.hashicorp.com/terraform/plugin/code-generation/openapi-generator

provider:
  name: binarylane
  schema:
    attributes:
      api_endpoint:
        source: env
        name: BINARYLANE_API_ENDPOINT
      api_token:
        source: env
        name: BINARYLANE_API_TOKEN
        sensitive: true

resources:
  server:
    create:
      path: /servers
      method: POST
    read:
      path: /servers/{server_id}
      method: GET
    delete:
      path: /servers/{server_id}
      method: DELETE
    schema:
      attributes:
        aliases:
          server_id: id
        overrides:
          backups:
            description: >
              If true this will enable two daily backups for the server. `options.daily_backups` will override this
              value if provided. Setting this to false has no effect.
          image:
            description: The slug of the selected operating system.
          ssh_keys:
            description: >
              This is a list of SSH key ids. If this is null or not provided, any SSH keys that have been marked as
              default will be deployed (assuming the operating system supports SSH Keys). Submit an empty list to
              disable deployment of default keys.
      ignores:
        - ipv6
        - licenses
        - links
        - server
        - options
        - password
  load_balancer:
    create:
      path: /load_balancers
      method: POST
    read:
      path: /load_balancers/{load_balancer_id}
      method: GET
    update:
      path: /load_balancers/{load_balancer_id}
      method: PUT
    delete:
      path: /load_balancers/{load_balancer_id}
      method: DELETE
    schema:
      attributes:
        aliases:
          load_balancer_id: id
      ignores:
        - links
        - load_balancer
  server_firewall_rules:
    create:
      path: /servers/{server_id}/actions#ChangeAdvancedFirewallRules
      method: POST
    read:
      path: /servers/{server_id}/advanced_firewall_rules
      method: GET
    update:
      path: /servers/{server_id}/actions#ChangeAdvancedFirewallRules
      method: POST
    delete:
      path: /servers/{server_id}/actions#ChangeAdvancedFirewallRules
      method: POST
    schema:
      ignores:
        - type
        - action
  ssh_key:
    create:
      path: /account/keys
      method: POST
    read:
      path: /account/keys/{key_id}
      method: GET
    delete:
      path: /account/keys/{key_id}
      method: DELETE
    schema:
      attributes:
        aliases:
          key_id: id
      ignores:
        - ssh_key
        - public_key
  vpc:
    create:
      path: /vpcs
      method: POST
    read:
      path: /vpcs/{vpc_id}
      method: GET
    update:
      path: /vpcs/{vpc_id}
      method: PATCH
    delete:
      path: /vpcs/{vpc_id}
      method: DELETE
    schema:
      attributes:
        aliases:
          vpc_id: id
      ignores:
        - route_entries
        - vpc
  vpc_route_entries:
    create:
      path: /vpcs/{vpc_id}
      method: PATCH
    read:
      path: /vpcs/{vpc_id}
      method: GET
    update:
      path: /vpcs/{vpc_id}
      method: PATCH
    delete:
      path: /vpcs/{vpc_id}
      method: DELETE
    schema:
      ignores:
        - name
        - vpc
data_sources:
  images:
    read:
      path: /images
      method: GET
    schema:
      ignores:
        - links
        - meta
        - page
        - per_page
        - private
  regions:
    read:
      path: /regions
      method: GET
    schema:
      ignores:
        - links
        - meta
        - page
        - per_page
  sizes:
    read:
      path: /sizes
      method: GET
    schema:
      ignores:
        - links
        - meta
        - page
        - per_page
