// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package data_sources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServerDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Required:            true,
				Description:         "The ID of the server to fetch.",
				MarkdownDescription: "The ID of the server to fetch.",
			},
		},
	}
}

type ServerModel struct {
	Id types.Int64 `tfsdk:"id"`
}
