#cloud-config
bootcmd:
  # If you have additional installation steps that need to be awaited, define
  # these in the `bootcmd` section and they will also be awaited.
  #
  - [cloud-init-per, instance, 'example-installing', sh, -c, 'sleep 60'] # pretend this is a slow installation step
  - [
      cloud-init-per,
      instance,
      'example-done',
      sh,
      -c,
      'echo Finished installing, Terraform will now proceed:`date` >> /var/tmp/user_data.log',
    ]

runcmd:
  - [sh, -c, 'sleep 99999'] # The provider won't wait for `runcmd` to complete
